/**
 * 28 Kelompok Soal DISC
 *
 * Setiap kelompok berisi 4 kata sifat yang mewakili dimensi D, I, S, C.
 * Kandidat memilih 1 MOST dan 1 LEAST dari setiap kelompok.
 *
 * Format: { groupNo, wordD, wordI, wordS, wordC }
 */

export const DISC_QUESTIONS = [
  {
    groupNo: 1,
    wordD: "Tegas",
    wordI: "Antusias",
    wordS: "Sabar",
    wordC: "Teliti",
  },
  {
    groupNo: 2,
    wordD: "Berani",
    wordI: "Meyakinkan",
    wordS: "Tenang",
    wordC: "Hati-hati",
  },
  {
    groupNo: 3,
    wordD: "Kompetitif",
    wordI: "Ramah",
    wordS: "Stabil",
    wordC: "Akurat",
  },
  {
    groupNo: 4,
    wordD: "Langsung",
    wordI: "Ekspresif",
    wordS: "Konsisten",
    wordC: "Sistematis",
  },
  {
    groupNo: 5,
    wordD: "Mandiri",
    wordI: "Optimis",
    wordS: "Loyal",
    wordC: "Analitis",
  },
  {
    groupNo: 6,
    wordD: "Ambisius",
    wordI: "Inspiratif",
    wordS: "Pendengar",
    wordC: "Perfeksionis",
  },
  {
    groupNo: 7,
    wordD: "Dominan",
    wordI: "Percaya diri",
    wordS: "Kooperatif",
    wordC: "Kritis",
  },
  {
    groupNo: 8,
    wordD: "Terus terang",
    wordI: "Humoris",
    wordS: "Toleran",
    wordC: "Logis",
  },
  {
    groupNo: 9,
    wordD: "Menentukan",
    wordI: "Populer",
    wordS: "Setia",
    wordC: "Cermat",
  },
  {
    groupNo: 10,
    wordD: "Gesit",
    wordI: "Persuasif",
    wordS: "Lembut",
    wordC: "Terorganisir",
  },
  {
    groupNo: 11,
    wordD: "Tangguh",
    wordI: "Ceria",
    wordS: "Pengertian",
    wordC: "Disiplin",
  },
  {
    groupNo: 12,
    wordD: "Gigih",
    wordI: "Spontan",
    wordS: "Harmonis",
    wordC: "Metodis",
  },
  {
    groupNo: 13,
    wordD: "Kuat",
    wordI: "Energik",
    wordS: "Tenang",
    wordC: "Presisi",
  },
  {
    groupNo: 14,
    wordD: "Pemberani",
    wordI: "Karismatik",
    wordS: "Suportif",
    wordC: "Objektif",
  },
  {
    groupNo: 15,
    wordD: "Agresif",
    wordI: "Komunikatif",
    wordS: "Penyabar",
    wordC: "Pemikir",
  },
  {
    groupNo: 16,
    wordD: "Otoriter",
    wordI: "Sosiabel",
    wordS: "Akomodatif",
    wordC: "Faktual",
  },
  {
    groupNo: 17,
    wordD: "Produktif",
    wordI: "Kreatif",
    wordS: "Reliable",
    wordC: "Investigatif",
  },
  {
    groupNo: 18,
    wordD: "Pantang menyerah",
    wordI: "Memikat",
    wordS: "Pendiam",
    wordC: "Waspada",
  },
  {
    groupNo: 19,
    wordD: "Proaktif",
    wordI: "Terbuka",
    wordS: "Stabil",
    wordC: "Konvensional",
  },
  {
    groupNo: 20,
    wordD: "Visioner",
    wordI: "Motivator",
    wordS: "Mediator",
    wordC: "Evaluator",
  },
  {
    groupNo: 21,
    wordD: "Inisiatif",
    wordI: "Interaktif",
    wordS: "Konsisten",
    wordC: "Strategis",
  },
  {
    groupNo: 22,
    wordD: "Kompeten",
    wordI: "Fleksibel",
    wordS: "Kooperatif",
    wordC: "Standar tinggi",
  },
  {
    groupNo: 23,
    wordD: "Fokus hasil",
    wordI: "Fokus orang",
    wordS: "Fokus proses",
    wordC: "Fokus kualitas",
  },
  {
    groupNo: 24,
    wordD: "Cepat bertindak",
    wordI: "Mudah bergaul",
    wordS: "Dapat dipercaya",
    wordC: "Berpikir mendalam",
  },
  {
    groupNo: 25,
    wordD: "Menantang",
    wordI: "Menghibur",
    wordS: "Mendukung",
    wordC: "Menganalisis",
  },
  {
    groupNo: 26,
    wordD: "Pemimpin",
    wordI: "Pembicara",
    wordS: "Penengah",
    wordC: "Perencana",
  },
  {
    groupNo: 27,
    wordD: "Berorientasi tujuan",
    wordI: "Berorientasi hubungan",
    wordS: "Berorientasi tim",
    wordC: "Berorientasi detail",
  },
  {
    groupNo: 28,
    wordD: "Pengambil risiko",
    wordI: "Penggerak semangat",
    wordS: "Penjaga stabilitas",
    wordC: "Penjaga standar",
  },
];
